### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ruizhideng** [liguowang/CrossMap#36]
Hi Liguo,

Thanks for this excellent package. 
I can successfully convert vcf file based on version 0.2.5, but now this version is deprecated. Then I have to use the updated version (0.5.2.), but it raised IndexError: list index out of range. I am pretty sure files are consistent, since it worked for old version.

**CrossMap.py vcf grch37_to_grch38.over.chain.gz  grch37.vcf GRCh38Decoy_no_alt.fa out_grch38.vcf**

Do you have any idea? 
I am looking forward to hearing from you!

**Comment by liguowang** [comment]
Please provide more information or a sample of the vcf file.

**Comment by Stikus** [comment]
Hello, same problem here.
We are using `CrossMap` for converting GRCh37 files to GRCh38 with https://hgdownload.cse.ucsc.edu/goldenpath/hg19/liftOver/hg19ToHg38.over.chain.gz chain file.

Our command is:
```
$CROSSMAP vcf $ref37ref38chain $currVCF37 $ref38GenomeFile $currVCF38
```
where

- `CROSSMAP="/usr/local/bin/CrossMap.py"`
- `ref37ref38chain=hg19ToHg38.over.chain.gz`
- `ref38GenomeFile=GRCh38.d1.vd1_mainChr.fa`

Main issue is that we cannot reproduce this error - we're converting multiple files with same positions (exactly same) and some files fails with error one time and next time - not (exact same files).
```
2021-11-12 06:59:45 [INFO]  Read the chain file "/ref/liftOver/hg19ToHg38.over.chain.gz"
2021-11-12 06:59:46 [INFO]  Filter out variants [reference_allele == alternative_allele] ...
2021-11-12 06:59:46 [INFO]  Index file is older than reference genome. Re-creating index for: /ref/GRCh38.d1.vd1_mainChr/GRCh38.d1.vd1_mainChr.fa
2021-11-12 07:00:08 [INFO]  Updating contig field ...
2021-11-12 07:00:08 [INFO]  Lifting over ...
Traceback (most recent call last):
  File "/usr/local/bin/CrossMap.py", line 209, in <module>
    crossmap_vcf_file(mapping = mapTree, infile= in_file, outfile = out_file, liftoverfile = chain_file, refgenome = genome_file, noCompAllele = options.no_comp_alleles, compress = options.compression)
  File "/usr/local/lib/python3.7/dist-packages/cmmodule/mapvcf.py", line 153, in crossmap_vcf_file
    target_chr = update_chromID(refFasta.references[0], target_chr)
IndexError: list index out of range
```

I cannot provide sample files due to NDA, but I can tell that all positions in these files are same - only genotypes varies. And when we convert same file several times, it can fail or can convert successfully. If I can give you any other information - I'll try.

Your tool is the best liftOver tool I've found, but this error is killing our use of it.

**Comment by Stikus** [comment]
Looks like here is the reason of this error: https://github.com/liguowang/CrossMap/blob/master/lib/cmmodule/mapvcf.py#L56:   
`refFasta = pysam.Fastafile(refgenome)` - if `pysam` fails to read Fasta for some reason (multithreading mode and big load for example) `refFasta` is empty and `refFasta.references[0]` is out of range.

**Comment by liguowang** [comment]
Yes. To be proactive, please reindex (using samtools) the reference fasta
file before using CrossMap. Or, delete the old index (.fai) file, and this
will force CrossMap to reindex the file.

Thanks

Liguo

**Comment by Stikus** [comment]
I've checked our reference files to find the reason for reindexing and understood that you are using `os.path.getctime` [here](https://github.com/liguowang/CrossMap/blob/master/lib/cmmodule/mapvcf.py#L52), but we are storing our reference in `tar.gz` with `.fai` and `.dict`. When you extract this tar `ctime` is modified to time of extraction but `mtime` remaining the same - [link](https://stackoverflow.com/questions/17958987/difference-between-python-getmtime-and-getctime-in-unix-system) - I suggest to change `os.path.getctime` to `os.path.getmtime` (I can create a PR if you agreed).

I'll try to manually reindex before running `CrossMap` and execute conversion of large amount of files for testing today. I'll return with results.

**Comment by Stikus** [comment]
I've checked our results and get somewhat consistent error appearance - if `pysam` tries to reindex fasta error sometimes pops up (we use 192 threaded xargs with 200 samples in parallel - several samples get error). If `pysam` do not reindex fasta (after first reindex or manual fix) everything working even with almost 4000 samples in parallel.

Due to fact that extracting `tar.gz` archive changes `ctime` and leaves `mtime` unchanged, I strongly recommend to change `os.path.getctime` to `os.path.getmtime` and we will implement our internal fix for it.

FYI - tar have option to not extract `mtime` from archive, but it cannot do anything with `ctime`.
```bash
root@49b2e8c88f1e:/outputs# tar --help
Usage: tar [OPTION...] [FILE]...
GNU 'tar' saves many files together into a single tape or disk archive, and can
restore individual files from the archive.

  -m, --touch                don't extract file modified time

```

**Comment by liguowang** [comment]
I will update and release a new version ASAP. Thanks

LIGUO

**Comment by Stikus** [comment]
Thanks for new release here: https://pypi.org/project/CrossMap/0.6.0/
We will test it in a few days.

But what about new release here on github (https://github.com/liguowang/CrossMap/releases - missing 2 last releases) and in docs (https://crossmap.readthedocs.io/en/latest/) ?

**Comment by serge2016** [comment]
I would ask the same. Could you make a release here, please.

**Comment by Stikus** [comment]
Looks like docs and releases fixed - maybe close issue?
