### ISSUE TITLE
meaning of viewchain output and strand information

### ISSUE THREAD

**Issue by euffelmann** [liguowang/CrossMap#69]
The `viewchain` flag converts a chain file into human readable format. Can you explain to me what exactly each column means (specifically which block refers to which build)?

For example, I used this code `CrossMap viewchain GRCh38_to_GRCh37.chain.gz` to produce this file:

```
1	10000	177417	+	1	10000	177417	+
1	257666	297968	+	1	227417	267719	+
1	347968	501617	+	1	317719	471368	-
1	585988	1630695	+	1	521368	1566075	+
1	1630696	1634405	+	1	1566075	1569784	+
1	1634408	1635542	+	1	1569784	1570918	+
1	1635546	1635550	+	1	1570918	1570922	+
1	1635560	1638937	+	1	1570922	1574299	+
1	1638938	1648308	+	1	1574299	1583669	+
1	1648309	1648518	+	1	1583669	1583878	+
```

To be more specific, I have a set of GWAS summary statistics that I need to liftover from GRCh38 to GRCh37. I do not only want to change their genomic position but also keep track of which SNPs' strand has changed. Hence, I thought `viewchain` would allow me to see which SNPs' strands differ between both builds. But I am confused about how to read this file (I expected to see a row for each SNP, which is not the case). 

Can you help me with this?
Thanks!

**Comment by liguowang** [comment]
Since the chain file you provided is "GRCh38_to_GRCh37.chain.gz", the first 4 columns (chrom, start, end, stand) of the output file are GRCh38-based, and the last 4 columns are GRCh37-based.

No, you won't see SNP information from the chain file (chain file only tells you how genomic segments from one assembly map to another assembly). You will manually assign your SNPs to the region they located, for example, if you see one SNP was inside the 3rd row, you know the strand has changed:

1	347968	501617	+	1	317719	471368	-

Hope this helps.

Liguo

**Comment by euffelmann** [comment]
Great, thank you for the quick reply!
